Story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Story4App.urls')),
]

Story4App/urls.py
from django.urls import path
from . import views

app_name = 'Story4App'

urlpatterns = [
    path('', views.index, name='Homepage'),
    path('profil/', views.profil, name='profil'),
    path('keahlian/', views.Keahlian, name='Keahlian'),
    path('pengalaman/', views.Pengalaman, name='Pengalaman'),
    path('kontak/', views.Kontak, name='Kontak'),
    path('pageTambahan/', views.pageTambahan, name='pageTambahan'),
]

Story4App/models.py
from django.db import models

# Create your models here.

Story4App/views.py
from django.shortcuts import render
from django.http import HttpResponse



def index(request):
    return render(request, 'Homepage.html')

def profil(request):
    return render(request, 'Profil.html')

def Keahlian(request):
    return render(request, 'Keahlian.html')

def Pengalaman(request):
    return render(request, 'Pengalaman.html')

def Kontak(request):
    return render(request, 'Kontak.html')

def pageTambahan(request):
    return render(request, 'pageTambahan.html')

Story4App/templates/Homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <nav class="navbar navbar-expand-lg navbar-light bg-light row justify-content-center sticky-top">
            <a href="{% url 'Story4App:profil' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Profil</p> 
            </a>
            <a href="{% url 'Story4App:Pengalaman' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Pengalaman</p> 
            </a>
            <a href="{% url 'Story4App:Keahlian' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Keahlian</p> 
            </a>
            <a href="{% url 'Story4App:Kontak' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Kontak</p> 
            </a>
            <a href="{% url 'Story4App:pageTambahan' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Page Tambahan</p> 
            </a> 
    </nav>
    <h1 style="font-size: 4.8vw" class="d-flex justify-content-center bg-light">Selamat Datang di Website ku!!!</h1>
    <img class= "rounded-circle" src="{% static 'images/image (1).png' %}" alt="maap" width="25%">
    <h1 style="font-size: 4.8vw" class="text-white">About Me!</h1>
    <P style="font-size: 2vw" class="bg-light">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
         Lorem Ipsum has been the industry's standard dummy text ever since the 
         1500s, when an unknown printer took a galley of type and scrambled it to 
         make a type specimen book. It has survived not only five centuries, but 
         also the leap into electronic typesetting, remaining essentially unchanged. 
         It was popularised in the 1960s with the release of Letraset sheets 
         containing Lorem Ipsum passages, and more recently with desktop publishing
         software like Aldus PageMaker including versions of Lorem Ipsum.
    </P>
</body>
</html>

Story4App/templates/Keahlian.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Keahlian</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
                <div class="card-body bg-light m-5">
                    <h1 style="font-size: 4.8vw" class="">Keahlian</h1>
                    <div class="d-flex justify-content-center">
                        <div class="card-body bg-secondary col-lg-4 d-flex">
                            <h2 style="font-size: 2.4vw"class="mr-3">Hard Skills</h2>
                            <P style="font-size: 2vw">
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                Lorem Ipsum has been the industry's standard dummy text ever since the 
                                1500s, when an unknown printer took a galley of type and scrambled it to 
                                make a type specimen book.
                            </P> 
                        </div>
                        <div class="card-body bg-secondary ml-5 col-lg-4 d-flex ">
                            <h2 style="font-size: 2.4vw"class="mr-3">Soft Skills</h2>
                            <P style="font-size: 2vw">
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                Lorem Ipsum has been the industry's standard dummy text ever since the 
                                1500s, when an unknown printer took a galley of type and scrambled it to 
                                make a type specimen book.
                            </P> 
                        </div>
                    </div>
                    <button style="font-size: 2vw" class="m-5" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
                </div>
            
</body>
</html>

Story4App/templates/Kontak.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kontak</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>

<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div class="card-body">
        <div class="card-body bg-light m-5 d-flex justify-content-center">
            <h1 style="font-size: 4.8vw">Contact me!!!</h1>
            <a href="https://www.instagram.com/sulthanzahrans/">
                <img class="img-fluid" src="{% static 'images/contact icon/instagram-icon-black-and-white-png-7.jpg' %}" class="rounded float-left">
            </a>
            <a href="https://www.facebook.com/profile.php?id=100007920976637" class="rounded float-center">
                <img class="img-fluid" src="{% static 'images/contact icon/icon-02-512.png' %}">
            </a>
            <a href="https://twitter.com/zahran0709">
                <img class="img-fluid" src="{% static 'images/contact icon/twitter-icon-png-black-13.jpg' %}" class="rounded float-center">
            </a>
        </div>
        <button style="font-size: 2vw" class="m-5" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
    </div>

</body>
</html>

Story4App/templates/Pengalaman.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pengalaman</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div class="card-body bg-light m-5">
        <h1 style="font-size: 4.8vw" class="">Pengalaman</h1>
        <div class="d-flex justify-content-center">
            <div class="card-body bg-secondary col-lg-4 d-flex">
                <h2 style="font-size: 2.4vw"class="mr-3">Organisasi</h2>
                <P style="font-size: 2vw">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 
                    1500s, when an unknown printer took a galley of type and scrambled it to 
                    make a type specimen book.
                </P> 
            </div>
            <div class="card-body bg-secondary ml-5 col-lg-4 d-flex ">
                <h2 style="font-size: 2.4vw" class="mr-3">Kepanitiaan</h2>
                <P style="font-size: 2vw">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 
                    1500s, when an unknown printer took a galley of type and scrambled it to 
                    make a type specimen book.
                </P> 
            </div>
        </div>
        <button style="font-size: 2vw" class="m-5" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
    </div>

</body>
</html>

Story4App/templates/Profil.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Profil</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div class="d-flex justify-content-center card-body bg-light m-5 p-5">
        <img style="width:25vw ; min-width: 100px;" class= "ml-1" src="{% static 'images/FOTO 3x4_190917_0005.jpg' %}" alt="maap" style="width: 20%">
        <div style="font-size: 2vw" class="card-body bg-secondary ml-2 col-lg-8 bg-light">   
            <h1 style="font-size: 4.8vw" >Profil</h1>
            
            Nama : Sulthan Zahran Sunata<br>
            
            NPM : 1806191585<br>
                        
            Angkatan : 2018<br>
                        
            Jurusan : Sistem Informasi<br>
                        
            Tempat Tanggal Lahir : Jakarta, 7 September 2000<br>
                        
            Alamat Tempat Tinggal : Jl. Daan Mogot<br>
                        
            Email : sulthan.zahran0709@gmail.com<br>
                        
            Nomor HP : 081288949960
        </div>
    </div>
    <button style="font-size: 2vw" class="d-flex justify-content-center m-5" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
</body>
</html>

Story4App/templates/pageTambahan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Page Tambahan</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div>
        <p style="font-size: 3.6vw" class="text-center text-white mt-5">
            Coming soon...
        </p>
    </div>
    <button style="font-size: 2vw" class="m-5" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
</body>
</html>